// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/28/2024, 9:04:40 AM
const configMerger = require("/Users/kaankoroglu/Desktop/testimonials/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/kaankoroglu/Desktop/testimonials/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaankoroglu/Desktop/testimonials/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaankoroglu/Desktop/testimonials/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaankoroglu/Desktop/testimonials/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaankoroglu/Desktop/testimonials/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kaankoroglu/Desktop/testimonials/plugins/**/*.{js,ts,mjs}","/Users/kaankoroglu/Desktop/testimonials/composables/**/*.{js,ts,mjs}","/Users/kaankoroglu/Desktop/testimonials/utils/**/*.{js,ts,mjs}","/Users/kaankoroglu/Desktop/testimonials/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kaankoroglu/Desktop/testimonials/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kaankoroglu/Desktop/testimonials/app.config.{js,ts,mjs}"] }));

module.exports = config
